---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-rbac-cm
data:
  policy.csv: |-
    g, nologs, role:nologs
    p, role:readonly, extensions, invoke, metrics, allow
    p, role:nologs, applications, *, */*, allow
    p, role:admin, logs, get, */*, allow
    p, role:admin, exec, create, */*, allow
    p, role:image-updater, applications, get, */*, allow
    p, role:image-updater, applications, update, */*, allow
    g, image-updater, role:image-updater

