apiVersion: v1
kind: ConfigMap
metadata:
  name: liquibase-changelog-config
data:
  db.changelog-master.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <databaseChangeLog
        xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog
            http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.8.xsd">
        
        <include file="changelog/changelog_1_create_example_table.xml"/>
    </databaseChangeLog>
  changelog_1_create_example_table.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <databaseChangeLog
        xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog
            http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.8.xsd">
        
        <changeSet id="1" author="yourname">
            <createTable tableName="example3">
                <column name="id" type="INT">
                    <constraints primaryKey="true" nullable="false"/>
                </column>
                <column name="name" type="VARCHAR(255)">
                    <constraints nullable="false"/>
                </column>
            </createTable>
        </changeSet>
    </databaseChangeLog>
